export const CREATE_EXAMPLE_NOTE = 'CREATE_EXAMPLE_NOTE'
export const CREATE_EMPTY_NOTE = 'CREATE_EMPTY_NOTE'

export const GET_NOTES_LIST_START = 'GET_NOTES_LIST_START'
export const GET_NOTES_LIST_END = 'GET_NOTES_LIST_END'

export const GET_CURRENT_NOTE_START = 'GET_CURRENT_NOTE_START'
export const GET_CURRENT_NOTE_END = 'GET_CURRENT_NOTE_END'
