export const RESET_STATE_NOTES = 'RESET_STATE_NOTES'
export const CREATE_EXAMPLE_NOTE = 'CREATE_EXAMPLE_NOTE'
export const CREATE_EMPTY_NOTE = 'CREATE_EMPTY_NOTE'

export const GET_NOTES_LIST_START = 'GET_NOTES_LIST_START'
export const GET_NOTES_LIST_END = 'GET_NOTES_LIST_END'

export const RESET_STATE_CURRENT = 'RESET_STATE_CURRENT'
export const UPDATE_CURRENT_NOTE = 'UPDATE_CURRENT_NOTE'
export const GET_CURRENT_NOTE = 'GET_CURRENT_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
